name: Carica ultimo capitolo di OnePiece

on:
  schedule:
    - cron: '0 21 * * 5'  # Esegue ogni venerdi alle 21:00
  workflow_dispatch:

permissions:
  contents: write  # Aggiunge i permessi per creare release e caricare asset

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python src/main.py ultimo

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Capitolo-${{ github.run_id }}
          release_name: Capitolo di questa settimana 
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ultimo.pdf
          asset_name: ultimo.pdf
          asset_content_type: application/pdf
